[workspace]
resolver = "3"
members = ["crates/sway-geo", "crates/sway-graph", "crates/sway-nodes", "crates/sway-midi", "crates/sway-app", "crates/sway-runtime", "crates/sway-gpu", "crates/sway-editor"]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
bevy = "=0.19.0"
bevy_app = "=0.19.0"
bevy_asset = "=0.19.0"
bevy_ecs = "=0.19.0"
bevy_math = "=0.19.0"
bevy_reflect = "=0.19.0"
bevy_time = "=0.19.0"
bevy_transform = "=0.19.0"
sway-geo = { path = "crates/sway-geo" }
sway-graph = { path = "crates/sway-graph" }
sway-nodes = { path = "crates/sway-nodes" }
crossbeam-channel = "0.5"
sway-midi = { path = "crates/sway-midi" }
sway-runtime = { path = "crates/sway-runtime" }
sway-gpu = { path = "crates/sway-gpu" }
sway-editor = { path = "crates/sway-editor" }
bytemuck = { version = "1", features = ["derive"] }
naga = { version = "29", features = ["wgsl-in"] }
wgpu = "=29.0.4"
pollster = "0.4"
kurbo = "0.13.1"
peniko = "0.6.1"
imaging = "0.0.1"
imaging_vello = { version = "0.0.2", default-features = false, features = ["vello-0-9"] }
winit = "=0.30.13"
ui-events-winit = "0.3.0"
masonry = { git = "https://github.com/linebender/xilem.git", rev = "c5950bcb03d4f3d187a20d1159f6aa276fd056bf" }
masonry_core = { git = "https://github.com/linebender/xilem.git", rev = "c5950bcb03d4f3d187a20d1159f6aa276fd056bf" }
masonry_testing = { git = "https://github.com/linebender/xilem.git", rev = "c5950bcb03d4f3d187a20d1159f6aa276fd056bf" }
ron = "0.12"
serde = { version = "1", features = ["derive"] }
