[workspace]
resolver = "3"
members = ["crates/sway-midi", "crates/sway-app", "crates/sway-runtime", "crates/sway-gpu"]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
bevy = "=0.19.0"
crossbeam-channel = "0.5"
sway-midi = { path = "crates/sway-midi" }
sway-runtime = { path = "crates/sway-runtime" }
sway-gpu = { path = "crates/sway-gpu" }
bytemuck = { version = "1", features = ["derive"] }
naga = { version = "29", features = ["wgsl-in"] }
wgpu = "=29.0.4"
pollster = "0.4"
kurbo = "0.13.1"
peniko = "0.6.1"
imaging = "0.0.1"
imaging_vello = { version = "0.0.2", default-features = false, features = ["vello-0-9"] }
