[package]
name = "sway-editor"
edition.workspace = true
version.workspace = true

[dependencies]
bevy_app.workspace = true
masonry.workspace = true
masonry_core.workspace = true
imaging.workspace = true
kurbo.workspace = true
peniko.workspace = true
ui-events-winit.workspace = true
winit.workspace = true
sway-graph.workspace = true
sway-viewport-input.workspace = true
sway-selection.workspace = true
sway-midi.workspace = true
crossbeam-channel.workspace = true
bevy_ecs.workspace = true
bevy_math.workspace = true
bevy_reflect.workspace = true
bevy_transform.workspace = true

[dev-dependencies]
masonry_testing.workspace = true
