[package]
name = "sway-editor"
edition.workspace = true
version.workspace = true

[dependencies]
masonry.workspace = true
masonry_core.workspace = true
imaging.workspace = true
kurbo.workspace = true
peniko.workspace = true
ui-events-winit.workspace = true
winit.workspace = true
sway-graph.workspace = true
bevy_ecs.workspace = true
bevy_math.workspace = true
bevy_reflect.workspace = true
bevy_transform.workspace = true
bevy_time.workspace = true

[dev-dependencies]
masonry_testing.workspace = true
bevy_app.workspace = true
sway-nodes.workspace = true
