[package]
name = "sway-app"
edition.workspace = true
version.workspace = true

[[bin]]
name = "sway"
path = "src/main.rs"

[dependencies]
bevy.workspace = true
crossbeam-channel.workspace = true
sway-graph.workspace = true
sway-midi.workspace = true
sway-nodes.workspace = true
sway-runtime.workspace = true
sway-gpu.workspace = true
sway-editor.workspace = true
winit.workspace = true
kurbo.workspace = true
peniko.workspace = true
imaging.workspace = true
